version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule: {interval: weekly}
  - package-ecosystem: npm
    directory: "/app/ui"
    schedule: {interval: weekly}
  - package-ecosystem: cargo
    directory: "/app/ui/src-tauri"
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: "/"
    schedule: {interval: weekly}
