// Content of the in-app Guide. One entry per button / feature so people can search for just the one they need.
// Keep it plain language. `screen` makes the "Open" button work; `kw` are extra search words.
import type { Screen } from "../app";

export type GuideEntry = { id: string; area: string; title: string; what: string; how?: string; screen?: Screen; section?: string; kw?: string };

export const GUIDE_AREAS = ["Getting started", "Top bar", "Chat", "Navigation screens", "Settings", "Safety & privacy", "Shortcuts & accessibility"];

export const GUIDE: GuideEntry[] = [
  // ---------------------------------------------------------------- getting started
  { id: "start-what", area: "Getting started", title: "What this app is", what: "A private assistant that runs on your own PC. Your chats, files and memory stay on this computer, encrypted with your password. The assistant can only do what you allow, and every step is recorded.", kw: "about overview intro" },
  { id: "start-first", area: "Getting started", title: "First steps", what: "1) Open Chat and say hello. 2) Add an AI model in Settings > AI Model if none is set up. 3) Try: \"Remind me in an hour to stretch\" - you will be asked to confirm. 4) Look at Settings > Appearance to pick a theme and colour.", screen: "chat", kw: "begin tutorial setup" },
  { id: "start-model", area: "Getting started", title: "Choosing an AI model", what: "The assistant needs a model to think with. Local models (for example through Ollama) never leave your PC. Add and test one under Settings > AI Model.", how: "Settings > AI Model has four separate cards: Chat models, Voice models, Vision models and Embedding models, each with its own Add button, Discover list (only models of that kind) and default. A model can never be added to the wrong kind or used for the wrong job. After Add, it tests itself in the background and becomes ready by itself.", screen: "settings", section: "model", kw: "ollama llm local model gpu add download discover test automatic whisper qwen asr speech" },
  { id: "start-lock", area: "Getting started", title: "Password, PIN and recovery key", what: "The password encrypts everything and cannot be recovered. The PIN is a quick way back in after the window locks. The recovery key (shown once) can reset a forgotten password - keep it somewhere safe and offline.", kw: "forgot reset credentials security" },

  // ---------------------------------------------------------------- top bar
  { id: "top-menu", area: "Top bar", title: "Menu button (three lines)", what: "Collapses the left navigation to icons only, or expands it again.", kw: "collapse sidebar hamburger" },
  { id: "top-crumb", area: "Top bar", title: "Where am I (breadcrumb)", what: "Shows the current screen next to the app name. The window title follows it too.", kw: "title location" },
  { id: "top-status", area: "Top bar", title: "Status pill (Idle / Running)", what: "Shows whether the assistant is idle, running tasks, disconnected from its background service, or stopped by an emergency stop. Click it to jump to Tasks (or to the emergency settings when stopped).", kw: "running idle tasks disconnected" },
  { id: "top-search", area: "Top bar", title: "Search / commands (magnifier, Ctrl+K)", what: "Opens a command box: jump to any screen, start a new chat, lock, or search your chats and files by typing 3 or more letters.", how: "Press Ctrl+K, type, use the arrow keys, press Enter.", kw: "command palette find ctrl k" },
  { id: "top-lock", area: "Top bar", title: "Lock", what: "Locks the app now. The assistant keeps working in the background if you let it, but the window needs your PIN or password to open again. Pending deletes are completed first.", how: "Ctrl+Shift+L.", kw: "sign out secure" },
  { id: "top-stop", area: "Top bar", title: "STOP ALL (red button)", what: "Emergency stop. Everything halts within 2 seconds; queued work is held, not deleted. The dialog also offers smaller stops: pause the agent, stop tasks, disable connectors, web access or the Python sandbox. Releasing a stop needs your password.", how: "Ctrl+Alt+Shift+S works even when the window is hidden.", screen: "settings", section: "emergency", kw: "kill switch panic halt" },

  // ---------------------------------------------------------------- chat
  { id: "chat-send", area: "Chat", title: "Sending a message", what: "Type in the box at the bottom and press Enter. Shift+Enter starts a new line. The assistant replies and shows what it did under Steps.", screen: "chat", kw: "composer write talk" },
  { id: "chat-new", area: "Chat", title: "New chat (+ button)", what: "Starts a fresh conversation. Old chats are kept in the chat list and in History.", screen: "chat", kw: "plus conversation" },
  { id: "chat-list", area: "Chat", title: "Chats list (menu button in the chat header)", what: "The list of past chats is hidden by default to keep the screen calm. Click the menu button at the left of the chat header to open it, choose a chat, and it closes again. Chats are grouped (Pinned, Today, Yesterday, folders...). Use the filter box to narrow them.", screen: "chat", kw: "sidebar drawer history conversations filter" },
  { id: "chat-rail", area: "Chat", title: "Position rail (thin lines at the right edge)", what: "In a chat with four or more questions a column of short lines appears at the right edge, one per question; the dark one marks the part you are reading. Hover over it (or Tab to it) to open a list with the first words of every question, click one to jump there; Up/Down arrows move between questions. It hides on narrow windows.", how: "Chat > right edge of the conversation.", screen: "chat", kw: "scroll navigate outline minimap jump long conversation questions lines" },
  { id: "chat-pin", area: "Chat", title: "Rename, pin and folders", what: "Hover a chat in the list (or in History): the pin keeps it at the top, the pencil renames it (also: double-click the title, press F2, or type /rename New name), the folder icon files it under a name you choose (up to 40 characters). The chat header has the same pencil and pin.", screen: "chat", kw: "organise organize group" },
  { id: "chat-tools", area: "Chat", title: "Tools switch", what: "Allows or blocks the assistant from using tools (reminders, web search, files...) in this chat. Off = it can only talk.", screen: "chat", kw: "permissions allow" },
  { id: "chat-steps", area: "Chat", title: "Steps panel", what: "A timeline of what the assistant did: reasoning, each tool call, the safety decision and your approvals. Hidden by default; open it with the Steps button in the chat header or /steps. Click a step to see details.", screen: "chat", kw: "timeline log transparency what did it do" },
  { id: "chat-archive", area: "Chat", title: "Archive and delete chat", what: "Archive hides the chat from the list without deleting it (see Show archived). Delete removes it for good after 8 seconds - an Undo button appears at the bottom right during that time.", screen: "chat", kw: "remove trash undo" },
  { id: "chat-slash", area: "Chat", title: "Slash commands", what: "Type / in the message box to see commands: /new, /remind, /mission, /search, /history, /steps, /pin, /rename, /theme, /lock, /help. Use arrow keys and Tab or Enter to pick one.", screen: "chat", kw: "shortcuts commands" },
  { id: "chat-scroll", area: "Chat", title: "Scroll buttons", what: "Round arrow buttons appear at the right of long conversations: one jumps to the top, one to the latest message (a number shows new messages you have not seen).", screen: "chat", kw: "jump bottom top" },
  { id: "chat-mic", area: "Chat", title: "Microphone (voice input)", what: "Click, speak, click again: your words are turned into text on this PC. Long dictation is safe: every ~30 seconds the audio so far is transcribed in the background and the text appears in the message box as you go, so nothing is lost if something goes wrong later (up to 60 minutes per recording); the text is kept as a draft until it is sent. Needs microphone permission, voice turned on in Settings and a speech model (for example frozenlab/qwen3-asr from Ollama: Settings > AI Model > Discover > Add model). Long recordings are cut into pieces automatically.", screen: "chat", kw: "speech dictation voice" },
  { id: "chat-usage", area: "Chat", title: "Usage bar under the message box", what: "Shows how much of today's model-token budget is used. It turns amber and red as you get close to the limit. Change limits in Settings > Autonomy & Budgets.", screen: "chat", kw: "tokens budget limit meter" },
  { id: "chat-folder", area: "Chat", title: "Share a folder with a chat (explicit approval)", what: "The folder button (or /folder, or dropping a folder) opens an approval: the assistant may read the files directly inside the folder. Subfolders are a separate tick (off by default); if the assistant needs one it asks you with a card. Approvals are for this chat and this session only - after you sign out or restart the chip says Allow again. AppData, Windows, Program Files, credential folders and whole drives are never shared; links that lead outside the folder are ignored.", how: "Chat > folder button.", screen: "chat", kw: "folder directory subfolder permission approve share access read local" },
  { id: "chat-pictures", area: "Chat", title: "Pictures and scanned documents", what: "Attach or drop a picture (.png .jpg .gif .webp), paste a screenshot (Ctrl+V) or upload a scanned PDF: the vision model reads the text and describes the picture automatically. Needs a vision model (Settings > AI Model > Vision models, for example qwen2.5vl or qwen3-vl). Without one the file is kept and you can press Read with vision model in My Files after adding one.", how: "Paperclip, drag and drop or Ctrl+V in the message box.", screen: "chat", kw: "image photo screenshot scan ocr picture vision pdf scanned paste" },
  { id: "chat-attach", area: "Chat", title: "Attach a file from this PC (paperclip, /attach, drag and drop)", what: "Pick a spreadsheet, CSV or document anywhere on your PC (Desktop, Documents...) or drag it onto the window. It is read where it is: nothing is uploaded or copied into My Files. Big Excel files (100 MB, a million rows) are read once, then the assistant answers exact questions - totals, filters, groupings - in seconds. A chip above the message box shows what is attached; the x stops sharing it (the file itself is never changed). Attached files belong to that one chat and are forgotten when you delete it.", how: "Click the paperclip next to the message box, choose the file, then ask: \"Total units per region in the attached file\".", screen: "chat", kw: "attach upload excel xlsx csv spreadsheet desktop local file read in place large big pdf docx drag drop" },
  { id: "chat-approval", area: "Chat", title: "Approval cards (Confirm / Deny / Edit)", what: "When the assistant wants to do something with side effects (set a reminder, send, delete...) it asks first. Confirm allows it once, Deny refuses, Edit lets you change the details before it runs. High-risk actions need your PIN.", screen: "approvals", kw: "allow permission confirm" },

  // ---------------------------------------------------------------- screens
  { id: "nav-home", area: "Navigation screens", title: "Home (widgets)", what: "Your day at a glance as small widgets: mail unread / addressed to me / waiting for my approval / deadlines / waiting for a reply (from Outlook), upcoming reminders, next routine runs, approvals waiting, what needs your attention, recent files with their summary, storage, what the assistant learned lately, AI models and PC health, activity today and updates. Press Widgets on the right to switch any widget on or off and change the order - only switched-on widgets are shown. Mail numbers are read in the background and refreshed every 5 minutes (Refresh forces it).", how: "Home > Widgets.", screen: "home", kw: "dashboard widgets mail unread reminders attention overview board customise" },
  { id: "nav-history", area: "Navigation screens", title: "History", what: "Every past chat and every piece of agent work in one timeline, grouped by day. Search it, filter chats or work, show archived items, and open any item.", screen: "history", kw: "past search archive" },
  { id: "nav-missions", area: "Navigation screens", title: "Missions & Routines", what: "Work that runs by itself on a schedule or when something happens, even with the window closed. Describe it in plain words (\"every weekday at 7:30 summarise important mail\"), review the form, then Activate. Pause, Run now, Edit or Cancel any time (Cancel has an Undo).", screen: "missions", kw: "schedule automation cron routine mission recurring" },
  { id: "mis-schedule", area: "Navigation screens", title: "Routine schedule: once a day or several times a day", what: "In New / Edit choose How often: Once a day (pick the time), More than once a day (repeat every 5 minutes up to 12 hours, optionally only between certain hours), or Advanced (type it in words or as a cron expression). Then pick the days: every day, weekdays, weekends or chosen days. The line under the form shows the plain-language result and the next run time.", screen: "missions", kw: "interval repeat hourly daily weekdays time cron every" },
  { id: "mis-format", area: "Navigation screens", title: "Routine output format", what: "Choose how the result is written: Report (Markdown), Short bullet list, Digest (headline + 3 bullets + sources), Detailed report with sources, Table, Email-style message, Plain text or JSON.", screen: "missions", kw: "format report digest table json markdown email output" },
  { id: "mis-web", area: "Navigation screens", title: "Routines that search the web", what: "Web search needs a search provider (Exa, Brave, Tavily or a SearXNG server) with its API key stored under Secrets, and the Web connector turned on for missions. Until then the routine is not run and Home shows what is missing. The form and the routine card have a button that opens Settings > Web Access.", how: "Secrets > Add: type = API key, paste the Exa key, tick \"web.search\" under Used by > Save. Settings > Web Access: Search provider = exa (asks for your password). Settings > Connectors > Web: turn on for chat/missions, then press Test web search.", screen: "settings", section: "web", kw: "exa brave tavily searxng api key search provider news research" },
  { id: "nav-reminders", area: "Navigation screens", title: "Reminders", what: "Your upcoming and fired reminders. Add one yourself, snooze, or dismiss. Reminders the assistant proposes always wait for your confirmation. Times are shown in your PC's local time.", screen: "reminders", kw: "alarm remind time" },
  { id: "nav-tasks", area: "Navigation screens", title: "Tasks", what: "What the assistant is running or has queued right now, with a button to cancel a task.", screen: "tasks", kw: "running queue background" },
  { id: "nav-approvals", area: "Navigation screens", title: "Approvals", what: "Everything waiting for your yes or no. A red number on the menu item shows how many. Each card explains the action, the data involved and how risky it is.", screen: "approvals", kw: "pending confirm" },
  { id: "nav-files", area: "Navigation screens", title: "My Files (with automatic summaries)", what: "Documents you give the assistant. Every file is quarantined, checked, scanned and read in an isolated process first. When it is ready, a local model writes a short summary, the kind of document (for example PAN card, invoice), keywords and the KINDS of personal data it contains (never the values), and the assistant keeps a memory of where the file is and what it is. Open a file to edit the summary or press Summarise again. Ask the assistant for \"my PAN card\" and it finds the file and shows it. Switch the summaries off in Settings > Files & Storage.", how: "My Files > click a file > Summary.", screen: "files", kw: "documents upload summary metadata pan card find quarantine auto summary pii" },
  { id: "nav-memory", area: "Navigation screens", title: "Memory (learns automatically, you decide what stays)", what: "The assistant learns lasting facts and preferences from what you type in chats, from routines you switch on, and from files you add to My Files - automatically. Each memory shows where it came from. Edit it, disable it, or Forget it: forgotten facts are never learned again. Secrets and ID-like numbers (PAN, Aadhaar, card, phone, e-mail) are never stored. Switch learning off with the toggle on this screen or in Settings > Memory. Memory can never change settings.", how: "Memory in the left menu.", screen: "memory", kw: "remember learn forget privacy preferences automatic about me" },
  { id: "nav-secrets", area: "Navigation screens", title: "Secrets", what: "Passwords and API keys you store for the assistant. Values are never shown to the model; revealing or changing one needs your PIN or password again.", screen: "secrets", kw: "api key password vault credentials" },
  { id: "nav-activity", area: "Navigation screens", title: "Activity log", what: "A record of everything the assistant did and every security event. Tabs: runs and steps, the security log (with an Integrity check that detects tampering), and \"What did the agent do?\" for a date range.", screen: "activity", kw: "audit log security events integrity report" },
  { id: "nav-outlook", area: "Navigation screens", title: "Outlook (email monitoring results)", what: "Shows what your email skills found: who needs your approval, which mails have deadlines, what is urgent. Each skill has a switch, Run now, and its latest result. A red number on the menu item counts results you have not looked at yet. The button can be hidden in Settings > Email monitoring (the skills keep running).", screen: "outlook", kw: "email mail outlook monitoring approval deadline inbox results" },
  { id: "set-emailmon", area: "Settings", title: "Email monitoring skills", what: "Ready-made read-only routines for classic Outlook, each with its own on/off switch: hourly inbox check, emails waiting for my approval, deadline radar, morning briefing, meeting preparation, follow-up tracker, mail that needs my reply, VIP sender alert, weekly wrap-up and inbox clean-up report. Nothing is sent, moved or deleted. Switching a skill on needs Local Outlook connected under Settings > Connectors.", how: "Settings > Email monitoring > switch a skill on. Change its schedule in Missions & Routines.", screen: "settings", section: "emailmon", kw: "outlook skills routine approval deadline vip hourly digest briefing" },
  { id: "app-proposals", area: "Navigation screens", title: "Routines proposed by the assistant", what: "When the assistant suggests a routine in chat it is saved as a proposal and does nothing until you press Activate. Proposals appear at the top of Approvals (and the Approvals number in the menu counts them), with Activate, Review / edit and Dismiss.", screen: "approvals", kw: "propose routine mission activate pending" },
  { id: "nav-guide", area: "Navigation screens", title: "Guide (this screen)", what: "Explains every button. Type a word in the search box (for example \"lock\" or \"theme\") to read only about that.", screen: "guide", kw: "help manual how to documentation" },
  { id: "nav-settings", area: "Navigation screens", title: "Settings", what: "Every setting lives here, grouped on the left. Anything that makes the app less safe asks for your PIN or password first.", screen: "settings", kw: "preferences options configure" },

  // ---------------------------------------------------------------- settings
  { id: "set-appearance", area: "Settings", title: "Appearance: theme, accent colour, background", what: "Pick a theme (System, Day & night, Light, Dark, Aurora, Ocean, Forest, Sunset), an accent colour (Blue, Teal, Emerald, Violet, Graphite, or the theme's own) and an optional animated background (off by default).", how: "Settings > Appearance & Voice.", screen: "settings", section: "ui", kw: "colour color theme dark light accent background animation look" },
  { id: "set-daynight", area: "Settings", title: "Day & night theme times", what: "With the Day & night theme the app switches between light and dark at the times you set, using your PC clock.", screen: "settings", section: "ui", kw: "time of day automatic" },
  { id: "set-textsize", area: "Settings", title: "Text size", what: "Scales text and most spacing from 80% to 160%.", screen: "settings", section: "ui", kw: "font bigger smaller zoom accessibility" },
  { id: "set-motion", area: "Settings", title: "Reduce motion", what: "Replaces sliding and scaling with short fades and stops all endless animation, including the background. It also turns on automatically when Windows is set to reduce animation.", screen: "settings", section: "ui", kw: "animation accessibility vestibular" },
  { id: "set-notifications", area: "Settings", title: "Windows notifications (named after what they are about)", what: "A reminder shows its own words as the title, a routine shows its name (\"Hourly inbox check - New results\"), an approval shows the chat or routine that needs you, and a chat answer shows the chat name when the window is not in front of you. Only names are shown, never the content of mail or documents. You can switch names off (generic text), choose how much content appears, set quiet hours or turn toasts off.", how: "Settings > Notifications: Show names, Notification content, Quiet hours, Windows notifications.", screen: "settings", section: "notifications", kw: "toast alert popup reminder name title windows notification quiet hours" },
  { id: "set-fonts", area: "Settings", title: "Fonts and text size", what: "Pick one of 20 popular office and professional fonts (Calibri, Arial, Verdana, Georgia, Cambria, Segoe UI ...) and Small, Medium or Large text. Each font is shown in itself; fonts that are not installed on this PC are marked and the app uses a similar one. Hindi and other Indian scripts always render.", how: "Settings > Appearance & Voice > Text size and Font.", screen: "settings", section: "ui", kw: "font typeface size small medium large text calibri arial verdana georgia" },
  { id: "set-voice", area: "Settings", title: "Voice", what: "Turns microphone input on or off.", screen: "settings", section: "ui", kw: "microphone speech" },
  { id: "set-pictures", area: "Settings", title: "Assistant icon and your picture", what: "Choose a picture from your PC for the assistant (shown in the top bar) and one for yourself (next to your name in the left menu). It is shrunk to 128 px on this PC and stored encrypted with your settings; only PNG, JPEG and WebP are accepted.", how: "Settings > Appearance & Voice > Pictures > Choose picture.", screen: "settings", section: "ui", kw: "icon avatar logo image photo profile upload" },
  { id: "app-gpu", area: "Navigation screens", title: "GPU meter (above Settings)", what: "A small transparent chart of your graphics card's activity, updated every two seconds. When you ask something and the AI model starts working, the line rises and \"AI working...\" appears - a sign that progress is being made. It can be switched off in Settings > Appearance & Voice.", screen: "settings", section: "ui", kw: "gpu graphics nvidia usage progress chart monitor" },
  { id: "act-network", area: "Navigation screens", title: "Network Logs (Activity log tab)", what: "Every network request this application made in the last 14 days: when, to which website or server, why (which tool or the AI model), the result (allowed, redirected, blocked by your rules, failed), how much data was sent and received, and how long it took. Summary tiles, a per-day chart, a table of destinations and the full list with filters; 'Copy as CSV' for your own analysis. Requests to the AI model on this PC are included (marked 'this PC'). Contents, passwords, tokens and web-address queries are never stored.", how: "Activity log > Network Logs.", screen: "activity", kw: "network traffic websites requests observability blocked egress internet audit domains" },
  { id: "set-account", area: "Settings", title: "Account & Security", what: "Change password or PIN, see the recovery key status, sign-in protection, auto-lock time, and the security posture report that lists anything weakening your protection.", screen: "settings", section: "account", kw: "password pin autolock posture" },
  { id: "set-connectors", area: "Settings", title: "Connectors", what: "Link outside services such as Microsoft 365 or local Outlook. Each is off until you connect it and can be disconnected any time.", screen: "settings", section: "connectors", kw: "microsoft outlook email calendar" },
  { id: "set-autonomy", area: "Settings", title: "Autonomy & Budgets", what: "How much the assistant may do on its own and its daily limits (tokens, web requests, data sent out, background tasks).", screen: "settings", section: "autonomy", kw: "limits budget concurrency" },
  { id: "set-web", area: "Settings", title: "Web Access", what: "Which websites the assistant may reach. Default is none; add domains you trust.", screen: "settings", section: "web", kw: "internet domains allowlist" },
  { id: "set-backup", area: "Settings", title: "Backup & Restore", what: "Create an encrypted backup file and restore from one. Restoring replaces current data and needs your password.", screen: "settings", section: "backup", kw: "export import save pabk" },
  { id: "set-privacy", area: "Settings", title: "Privacy & Data", what: "See what is stored, export your data, or delete everything (this returns the app to first-run setup).", screen: "settings", section: "privacy", kw: "delete export gdpr wipe" },
  { id: "set-updates", area: "Settings", title: "Updates", what: "Check for and install signed updates. Nothing is sent about you.", screen: "settings", section: "updates", kw: "upgrade version" },
  { id: "set-diag", area: "Settings", title: "Diagnostics & About", what: "Versions, a self-test and the information to include when asking for help.", screen: "settings", section: "diagnostics", kw: "version support troubleshoot" },

  // ---------------------------------------------------------------- safety
  { id: "safe-approvals", area: "Safety & privacy", title: "Why the assistant asks for approval", what: "Anything with side effects (changing, sending or deleting) waits for you. Reading public information may run automatically depending on your settings.", kw: "permission consent risk" },
  { id: "safe-labels", area: "Safety & privacy", title: "Data labels: Public, Internal, Confidential, Restricted", what: "Every file and chat carries a sensitivity label. The higher the label, the tighter the rules: web access and sending data out need approval or are blocked.", kw: "sensitivity classification dlp" },
  { id: "safe-quarantine", area: "Safety & privacy", title: "Quarantine and scanning", what: "New files wait in quarantine, are checked and scanned, then read by an isolated helper process. A file that fails stays out and the reason is shown.", screen: "files", kw: "malware antivirus defender reject" },
  { id: "safe-stepup", area: "Safety & privacy", title: "Asked for PIN or password again", what: "A few actions (revealing a secret, exporting data, loosening a safety setting, high-risk approvals) ask you to prove it is you again, even though you are signed in.", kw: "reauthenticate step-up verify" },
  { id: "safe-undo", area: "Safety & privacy", title: "Undo for deleting", what: "Deleting a chat, file or memory (and cancelling a mission) can be undone for 8 seconds with the Undo button in the corner. After that - or when you lock or close the window - it is permanent.", kw: "restore recover deleted" },
  { id: "safe-time", area: "Safety & privacy", title: "Times and time zone", what: "All times you see use your PC's clock and time zone. The assistant is told your local time, so \"in an hour\" or \"at 3 pm\" means your time.", kw: "clock timezone local reminder" },

  // ---------------------------------------------------------------- shortcuts
  { id: "key-all", area: "Shortcuts & accessibility", title: "Keyboard shortcuts", what: "Left menu: Alt+H Home, Alt+C Chat, Alt+I History, Alt+M Missions & Routines, Alt+R Reminders, Alt+T Tasks, Alt+A Approvals, Alt+F My Files, Alt+E Memory, Alt+S Secrets, Alt+L Activity log, Alt+O Outlook, Alt+G Guide, Alt+, Settings. Also: Alt+N new chat, F1 Guide, Ctrl+K command box, Ctrl+Shift+L lock, Ctrl+Alt+Shift+S emergency stop, Enter send, Shift+Enter new line, Esc close a dialog. The key is shown next to each menu item and in its tooltip. (Ctrl+C is not used for Chat because it means Copy.)", kw: "keys hotkey alt ctrl shortcut keyboard" },
  { id: "key-a11y", area: "Shortcuts & accessibility", title: "Accessibility", what: "All colours meet WCAG AA contrast. The app follows Windows settings for reduced animation, reduced transparency and higher contrast, scales text up to 160%, and every control can be reached with the keyboard.", kw: "screen reader contrast keyboard" },
  { id: "key-tray", area: "Shortcuts & accessibility", title: "Tray icon and closing the window", what: "Closing the window may leave the assistant running in the system tray so reminders and routines still work. Use the tray menu to open the window, or to quit completely.", kw: "background exit close quit" },
];
